# Generated by Django 5.1.15 on 2026-06-05 16:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero_lote', models.CharField(blank=True, max_length=80, verbose_name='Número do lote')),
                ('data_fabricacao', models.DateField(blank=True, null=True, verbose_name='Data de fabricação')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de validade')),
                ('data_entrada', models.DateField(verbose_name='Data de entrada')),
                ('quantidade_inicial', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantidade inicial')),
                ('quantidade_atual', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantidade atual')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, verbose_name='Nota fiscal')),
                ('observacoes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='core.produto', verbose_name='Produto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['data_validade', 'data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('ESTOQUE_MIN', 'Estoque no mínimo'), ('ESTOQUE_CRITICO', 'Estoque crítico'), ('ESGOTADO', 'Produto esgotado'), ('RUPTURA', 'Risco de ruptura'), ('VENCIDO', 'Produto vencido'), ('VENCIMENTO_30', 'Vencimento em 30 dias'), ('VENCIMENTO_15', 'Vencimento em 15 dias'), ('VENCIMENTO_7', 'Vencimento em 7 dias'), ('VENCIMENTO_3', 'Vencimento em 3 dias'), ('RISCO_PERDA', 'Risco de perda por vencimento'), ('EXCESSO', 'Estoque em excesso'), ('CONSUMO_ALTO', 'Consumo acima da média'), ('CONSUMO_BAIXO', 'Consumo abaixo da média'), ('COMPRA', 'Compra necessária'), ('COMPRA_URGENTE', 'Compra urgente'), ('PRECO_SUBIU', 'Aumento significativo de preço'), ('PRECO_DESCEU', 'Redução significativa de preço')], max_length=20, verbose_name='Tipo')),
                ('nivel', models.CharField(choices=[('INFO', 'Informativo'), ('ATENCAO', 'Atenção'), ('URGENTE', 'Urgente'), ('CRITICO', 'Crítico')], max_length=10, verbose_name='Nível')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido')),
                ('resolvido', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='Dados extras')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.produto', verbose_name='Produto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='stock.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=8, verbose_name='Tipo')),
                ('motivo', models.CharField(max_length=30, verbose_name='Motivo')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor unitário (R$)')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor total (R$)')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, verbose_name='Nota fiscal')),
                ('responsavel', models.CharField(blank=True, max_length=120, verbose_name='Responsável / Setor')),
                ('data_movimento', models.DateTimeField(verbose_name='Data do movimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cancelado', models.BooleanField(default=False, verbose_name='Cancelado')),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=255, verbose_name='Motivo do cancelamento')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='core.fornecedor', verbose_name='Fornecedor')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='stock.lote', verbose_name='Lote')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.produto', verbose_name='Produto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_movimento'],
            },
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['produto', 'data_validade'], name='stock_lote_produto_e6284a_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['data_validade'], name='stock_lote_data_va_b8ac78_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['lido', '-created_at'], name='stock_alert_lido_9e3d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['tipo'], name='stock_alert_tipo_95f477_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['produto', '-data_movimento'], name='stock_movim_produto_d94722_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['tipo', '-data_movimento'], name='stock_movim_tipo_bdcba1_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['-data_movimento'], name='stock_movim_data_mo_8491fc_idx'),
        ),
    ]
