# Generated by Django 5.1.15 on 2026-06-05 16:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSingleton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome da empresa')),
                ('empresa_cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('empresa_telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('empresa_endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('alerta_vencimento_30', models.PositiveIntegerField(default=30)),
                ('alerta_vencimento_15', models.PositiveIntegerField(default=15)),
                ('alerta_vencimento_7', models.PositiveIntegerField(default=7)),
                ('alerta_vencimento_3', models.PositiveIntegerField(default=3)),
                ('janela_consumo_dias', models.PositiveIntegerField(default=30, help_text='Período usado para calcular consumo médio', verbose_name='Janela de cálculo de consumo (dias)')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('cor', models.CharField(blank=True, help_text='Código hexadecimal (#RRGGBB) usado no dashboard', max_length=7, verbose_name='Cor de identificação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome / Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nome fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, verbose_name='Inscrição Estadual')),
                ('contato_nome', models.CharField(blank=True, max_length=120, verbose_name='Nome do contato')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('lead_time_days', models.PositiveIntegerField(default=7, help_text='Tempo médio de entrega do fornecedor', verbose_name='Prazo de reposição (dias)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('codigo_interno', models.CharField(max_length=50, unique=True, verbose_name='Código interno')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, verbose_name='Código de barras')),
                ('unidade_medida', models.CharField(choices=[('KG', 'Quilograma (kg)'), ('G', 'Grama (g)'), ('L', 'Litro (L)'), ('ML', 'Mililitro (mL)'), ('UN', 'Unidade'), ('CX', 'Caixa'), ('PC', 'Pacote'), ('DZ', 'Dúzia'), ('FD', 'Fardo')], default='UN', max_length=3, verbose_name='Unidade de medida')),
                ('controla_validade', models.BooleanField(default=True, help_text='Se marcado, o sistema exigirá lote e data de validade nas entradas', verbose_name='Controla validade')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Quantidade mínima antes de alertar compra', max_digits=12, verbose_name='Estoque mínimo')),
                ('estoque_ideal', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Quantidade desejada após reposição', max_digits=12, verbose_name='Estoque ideal')),
                ('localizacao', models.CharField(blank=True, help_text='Ex: Prateleira A3, Câmara fria 2', max_length=100, verbose_name='Localização física')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.categoria', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('fornecedor_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='core.fornecedor', verbose_name='Fornecedor principal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['codigo_interno'], name='core_produt_codigo__334451_idx'), models.Index(fields=['nome'], name='core_produt_nome_25aec1_idx'), models.Index(fields=['categoria'], name='core_produt_categor_affd88_idx')],
            },
        ),
    ]
