# Generated by Django 5.1.15 on 2026-06-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('KG', 'Quilograma (kg)'), ('G', 'Grama (g)'), ('L', 'Litro (L)'), ('ML', 'Mililitro (mL)'), ('UN', 'Unidade'), ('CX', 'Caixa'), ('PC', 'Pacote'), ('PAC', 'Pacote (PAC)'), ('DZ', 'Dúzia'), ('FD', 'Fardo'), ('ROL', 'Rolo')], default='UN', max_length=3, verbose_name='Unidade de medida'),
        ),
    ]
