# Generated by Django 5.1.15 on 2026-06-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='periodo_padrao',
            field=models.PositiveIntegerField(choices=[(7, 'Últimos 7 dias'), (15, 'Últimos 15 dias'), (30, 'Últimos 30 dias'), (90, 'Últimos 90 dias'), (180, 'Últimos 6 meses'), (365, 'Último ano')], default=30, help_text='Usado no dashboard, gráficos e relatórios.', verbose_name='Período padrão para análise (dias)'),
        ),
    ]
