# Generated by Django 5.1.15 on 2026-06-05 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CRIAR', 'Criou registro'), ('EDITAR', 'Editou registro'), ('EXCLUIR', 'Excluiu registro'), ('MOVER', 'Movimentou estoque'), ('CANCELAR', 'Cancelou registro')], max_length=20, verbose_name='Ação')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('objeto_id', models.CharField(blank=True, max_length=64, verbose_name='ID do objeto')),
                ('objeto_repr', models.CharField(blank=True, max_length=255, verbose_name='Descrição do objeto')),
                ('dados_anteriores', models.JSONField(blank=True, default=dict, verbose_name='Dados anteriores')),
                ('dados_novos', models.JSONField(blank=True, default=dict, verbose_name='Dados novos')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='URL')),
                ('metodo', models.CharField(blank=True, max_length=10, verbose_name='Método HTTP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Quando')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de auditoria',
                'verbose_name_plural': 'Logs de auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_logau_timesta_4ced89_idx'), models.Index(fields=['modelo', 'objeto_id'], name='audit_logau_modelo_873d53_idx')],
            },
        ),
    ]
